#!/bin/bash -u
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/util

tf_dirs=(${INPUT_DIRS//:/ })
errors=0
for dir in ${tf_dirs[@]}; do
    planfile="${ARTIFACTS_DIR}/${dir}.tfplan"
    if [[ -f ${planfile} ]]; then
        pushd ${dir} > /dev/null
        configure_environment
        terraform_init &&
        terraform_apply ${planfile} || ((errors++))
        popd > /dev/null
    fi
done

echo "::set-output name=errors::${errors}"