#!/bin/bash -u
export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${SCRIPT_DIR}/util

# Dump the environment if we're in debug mode.
for var in $(printenv); do
    echo "::debug:: ${var}"
done

# SSH_PRIV_KEY: ssh private key with access to required module repos.
# SSH_PRIV_KEY_B64: Base64 encoded SSH_PRIV_KEY.  Ignored if SSH_PRIV_KEY is set.
# INPUT_DIRS: Colon separated list of directories (set by GitHub Actions).
# ARTIFACTS_DIR: Where to store plans and other artifacts. This should be within /github/workspace
# TERRAFORM_TOKEN: API Token for Terraform cloud.
# GITHUB_TOKEN: API Token for GitHub.  Normally supplied by Actions.
# GITHUB_EVENT_PATH: Path to JSON file describing the event. Normally supplied by Actions.
# TERRAFORM_VERSION: Version of terraform to use.
# GSUITE_PROVIDER_VERSION: Version of Terraform GSuite provider to use.                   |
# KUBECTL_VERSION: Version of kubectl to use.
# HELM_VERSION: Version of helm to use.
# DIRENV_VERSION: Version of direnv to use.
# ENVKEY_VERSION: Version of envkey-source to use.

configure_ssh
configure_terraform
configure_kubectl

if [ ! -z ${ARTIFACTS_DIR:-} ]; then
    mk_artifacts_dir ${ARTIFACTS_DIR}
fi

exec ${SCRIPT_DIR}/${INPUT_CMD}
