#!/bin/bash -ue
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/util

# These vars are required:
# INPUT_DIRS: Colon separated list of directories (set by GitHub Actions).
# SSH_PRIV_KEY: ssh private key with access to required module repos.
# TERRAFORM_TOKEN: API Token for Terraform cloud.
# TERRAFORM_VERSION: Version of terraform to use.
# ARTIFACTS_DIR: Where to store plans and other artifacts.
# KUBECTL_VERSION: Version of kubectl to use.
# HELM_VERSION: Version of helm to use.
# DIRENV_VERSION: Version of direnv to use.
# ENVKEY_VERSION: Version of envkey-source to use.

configure_ssh
configure_terraform
configure_kubectl

mk_artifacts_dir ${ARTIFACTS_DIR}

get_terraform             ${TERRAFORM_VERSION}             || exit $?
get_kubectl               ${KUBECTL_VERSION}               || exit $?
get_helm                  ${HELM_VERSION}                  || exit $?
get_direnv                ${DIRENV_VERSION}                || exit $?
get_envkey                ${ENVKEY_VERSION}                || exit $?
get_aws_iam_authenticator ${AWS_IAM_AUTHENTICATOR_VERSION} || exit $?

# Process each directory in INPUT_DIRS.
tf_dirs=(${INPUT_DIRS//:/ })
for dir in ${tf_dirs[@]}; do
    pushd $dir > /dev/null
    if [ -f .envrc ]; then
        direnv allow
        eval $(direnv export bash)
    fi
    terraform_init
    terraform_plan
    popd > /dev/null
done
