#!/bin/bash -u
source ${SCRIPT_DIR}/util

tf_dirs=(${INPUT_DIRS//:/ })
errors=0
applies=0
for dir in ${tf_dirs[@]}; do
    planfile="${ARTIFACTS_DIR}/${dir}.tfplan"
    if [[ -f ${planfile} ]]; then
        pushd ${dir} > /dev/null
        configure_environment
        terraform_init &&
        terraform_apply ${planfile} || ((errors++))
        popd > /dev/null
    fi
done

echo "::set-output name=errors::${errors}"
echo "::set-output name=applies::${applies}"