#!/bin/bash -u
source ${SCRIPT_DIR}/util

# Process each directory in INPUT_DIRS.
tf_dirs=(${INPUT_DIRS//:/ })
errors=0
diffs=0
for dir in ${tf_dirs[@]}; do
    pushd $dir > /dev/null
    configure_environment
    terraform_init &&\
    terraform_plan || ((errors++))
    popd > /dev/null
done

if [ ${errors} -eq 0 ] && [ ${diffs} -eq 0 ]; then
    echo '::warning:: No changes or errors detected... Nothing to do.'
    exit 0
fi

echo "::set-output name=errors::${errors}"
echo "::set-output name=plans::${diffs}"